version: "3.8"

services:
  airflow:
    build: .
    container_name: airflow
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True

      # Tell dbt inside Airflow to use the same profiles.yml you use locally
      - DBT_PROFILES_DIR=/opt/airflow/dbt

    volumes:
      # DAGs directory
      - ./dags:/opt/airflow/dags

      # Mount your entire dbt project (including profiles.yml)
      - ../dbt:/opt/airflow/dbt

    ports:
      - "8080:8080"

    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com || true &&
      airflow webserver & airflow scheduler
      "
